on:
  push:
    branch:
      -master

env:
  WORLD_TEXT: world world world world

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Build Docker Image
    #   uses: docker/build-push-action@v1.1.0
    #   with:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    #     repository: nepet/docker-action-test/test
    #     registry: docker.pkg.github.com
    #     tag_with_ref: true
    #     build_args: "\
    #         HELLO=${{ secrets.HELLO_SECRET }},\
    #         WORLD=${{ env.WORLD_TEXT }}"
    - name: publish
      uses: appleboy/ssh-action@master
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_LABEL: ${{ secrets.DOCKER_LABEL }}
      with:
        username: ${{ secrets.DEPLOY_USER }}
        host: ${{ secrets.DEPLOY_HOST }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          echo "I AM $DOCKER_LABEL" > test.txt
          echo "ANOTHER I AM $DOCKER_LABEL"
          docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
          docker ps -a -q -f label=$DOCKER_LABEL | xargs -r docker stop  
        # docker run -dit --rm -l label=$DOCKER_LABEL -p 5000:5000 docker.pkg.github.com/bbh-website/website:pr-6-merge
