on:
  push:
    branch:
      -master

env:
  WORLD_TEXT: world world world world

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mr-smithers-excellent/docker-build-push@v3
      name: Build Docker Image
      id: docker_build
      env:
        HELLO_SECRET=${{ secrets.HelloSecret }}
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        image: nepet/docker-action-test/test
        registry: docker.pkg.github.com
        buildArgs: "\
          HELLO=$HELLO_SECRET,\
          WORLD=${{ env.WORLD_TEXT }}"
    - uses: appleboy/ssh-action@master
      name: publish
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_LABEL: ${{ secrets.DOCKER_LABEL }}
        DOCKER_IMAGE: ${{ steps.docker_build.outputs.imageFullName }}
      with:
        username: ${{ secrets.DEPLOY_USER }}
        host: ${{ secrets.DEPLOY_HOST }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        envs: GITHUB_USERNAME,GITHUB_TOKEN,DOCKER_LABEL,DOCKER_IMAGE
        script: |
          echo $DOCKER_IMAGE
          echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u $GITHUB_USERNAME --password-stdin
          docker ps -a -q -f label=$DOCKER_LABEL | xargs -r docker stop  
          docker run -d -l label=$DOCKER_LABEL $DOCKER_IMAGE
